services:
  zou:
    build: .
    ports:
      - "5080:80"
    volumes:
      - ./data/zou/previews:/opt/zou/previews
    environment:
      DB_USERNAME: ${ZOU_USERNAME}
      DB_HOST: db
      DB_PASSWORD: ${ZOU_PASSWORD}
      DB_SCHEMA: ${ZOU_DATABASE}
      KITSU_DEFAULT_PASSWORD: ${KITSU_DEFAULT_PASSWORD}
    depends_on:
      - db     
  db:
    image: "postgres:12"
    command: postgres -c stats_temp_directory=/tmp
    ports:
      - "5442:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "var/lib/postgresql/data/pgdata"
      ZOU_USERNAME: ${ZOU_USERNAME}
      ZOU_PASSWORD: ${ZOU_PASSWORD}
      ZOU_DATABASE: ${ZOU_DATABASE}
