#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" << EOF
    CREATE USER kitsu WITH PASSWORD '$ZOU_PASSWORD';
    CREATE DATABASE $ZOU_DATABASE;
    GRANT ALL PRIVILEGES ON DATABASE $ZOU_DATABASE TO $ZOU_USERNAME;
EOF